### ISSUE TITLE
Couldn't save element

### ISSUE THREAD

**Issue by readtedium** [venveo/craft-bulkedit#1]
Every time I've tried to use this plugin, it's given me an error saying the change didn't go through. Here's the relevant portion of the queue.log, if it helps:

```
2018-11-16 21:44:47 [-][1][-][info][yii\db\Command::execute] UPDATE `bulkedit_history` SET `dateUpdated`='2018-11-17 02:44:47', `status`='completed', `originalValue`='{\"editable\":false,\"sectionId\":null,\"typeId\":null,\"authorId\":null,\"authorGroupId\":null,\"postDate\":null,\"before\":null,\"after\":null,\"expiryDate\":null,\"elementType\":\"craft\\\\elements\\\\Entry\",\"query\":null,\"subQuery\":null,\"contentTable\":\"{{%content}}\",\"customFields\":null,\"inReverse\":false,\"asArray\":false,\"id\":null,\"uid\":null,\"fixedOrder\":false,\"status\":[\"live\"],\"archived\":false,\"dateCreated\":null,\"dateUpdated\":null,\"siteId\":1,\"enabledForSite\":true,\"leaves\":false,\"relatedTo\":null,\"title\":null,\"slug\":null,\"uri\":null,\"search\":null,\"ref\":null,\"with\":null,\"orderBy\":{\"relations.sortOrder\":4},\"withStructure\":true,\"structureId\":null,\"level\":null,\"hasDescendants\":null,\"ancestorOf\":null,\"ancestorDist\":null,\"descendantOf\":null,\"descendantDist\":null,\"siblingOf\":null,\"prevSiblingOf\":null,\"nextSiblingOf\":null,\"positionedBefore\":null,\"positionedAfter\":null,\"select\":[\"**\"],\"selectOption\":null,\"distinct\":null,\"from\":null,\"groupBy\":null,\"join\":[[\"INNER JOIN\",\"{{%relations}} relations\",[\"and\",\"[[relations.targetId]] = [[elements.id]]\",{\"relations.sourceId\":\"1281\",\"relations.fieldId\":\"15\"},[\"or\",{\"relations.sourceSiteId\":null},{\"relations.sourceSiteId\":1}]]]],\"having\":null,\"union\":null,\"params\":[],\"queryCacheDuration\":null,\"queryCacheDependency\":null,\"where\":null,\"limit\":\"1\",\"offset\":null,\"indexBy\":null,\"emulateExecution\":false}' WHERE `id`=26
2018-11-16 21:44:47 [-][1][-][profile begin][yii\db\Command::execute] UPDATE `bulkedit_history` SET `dateUpdated`='2018-11-17 02:44:47', `status`='completed', `originalValue`='{\"editable\":false,\"sectionId\":null,\"typeId\":null,\"authorId\":null,\"authorGroupId\":null,\"postDate\":null,\"before\":null,\"after\":null,\"expiryDate\":null,\"elementType\":\"craft\\\\elements\\\\Entry\",\"query\":null,\"subQuery\":null,\"contentTable\":\"{{%content}}\",\"customFields\":null,\"inReverse\":false,\"asArray\":false,\"id\":null,\"uid\":null,\"fixedOrder\":false,\"status\":[\"live\"],\"archived\":false,\"dateCreated\":null,\"dateUpdated\":null,\"siteId\":1,\"enabledForSite\":true,\"leaves\":false,\"relatedTo\":null,\"title\":null,\"slug\":null,\"uri\":null,\"search\":null,\"ref\":null,\"with\":null,\"orderBy\":{\"relations.sortOrder\":4},\"withStructure\":true,\"structureId\":null,\"level\":null,\"hasDescendants\":null,\"ancestorOf\":null,\"ancestorDist\":null,\"descendantOf\":null,\"descendantDist\":null,\"siblingOf\":null,\"prevSiblingOf\":null,\"nextSiblingOf\":null,\"positionedBefore\":null,\"positionedAfter\":null,\"select\":[\"**\"],\"selectOption\":null,\"distinct\":null,\"from\":null,\"groupBy\":null,\"join\":[[\"INNER JOIN\",\"{{%relations}} relations\",[\"and\",\"[[relations.targetId]] = [[elements.id]]\",{\"relations.sourceId\":\"1281\",\"relations.fieldId\":\"15\"},[\"or\",{\"relations.sourceSiteId\":null},{\"relations.sourceSiteId\":1}]]]],\"having\":null,\"union\":null,\"params\":[],\"queryCacheDuration\":null,\"queryCacheDependency\":null,\"where\":null,\"limit\":\"1\",\"offset\":null,\"indexBy\":null,\"emulateExecution\":false}' WHERE `id`=26
2018-11-16 21:44:47 [-][1][-][profile end][yii\db\Command::execute] UPDATE `bulkedit_history` SET `dateUpdated`='2018-11-17 02:44:47', `status`='completed', `originalValue`='{\"editable\":false,\"sectionId\":null,\"typeId\":null,\"authorId\":null,\"authorGroupId\":null,\"postDate\":null,\"before\":null,\"after\":null,\"expiryDate\":null,\"elementType\":\"craft\\\\elements\\\\Entry\",\"query\":null,\"subQuery\":null,\"contentTable\":\"{{%content}}\",\"customFields\":null,\"inReverse\":false,\"asArray\":false,\"id\":null,\"uid\":null,\"fixedOrder\":false,\"status\":[\"live\"],\"archived\":false,\"dateCreated\":null,\"dateUpdated\":null,\"siteId\":1,\"enabledForSite\":true,\"leaves\":false,\"relatedTo\":null,\"title\":null,\"slug\":null,\"uri\":null,\"search\":null,\"ref\":null,\"with\":null,\"orderBy\":{\"relations.sortOrder\":4},\"withStructure\":true,\"structureId\":null,\"level\":null,\"hasDescendants\":null,\"ancestorOf\":null,\"ancestorDist\":null,\"descendantOf\":null,\"descendantDist\":null,\"siblingOf\":null,\"prevSiblingOf\":null,\"nextSiblingOf\":null,\"positionedBefore\":null,\"positionedAfter\":null,\"select\":[\"**\"],\"selectOption\":null,\"distinct\":null,\"from\":null,\"groupBy\":null,\"join\":[[\"INNER JOIN\",\"{{%relations}} relations\",[\"and\",\"[[relations.targetId]] = [[elements.id]]\",{\"relations.sourceId\":\"1281\",\"relations.fieldId\":\"15\"},[\"or\",{\"relations.sourceSiteId\":null},{\"relations.sourceSiteId\":1}]]]],\"having\":null,\"union\":null,\"params\":[],\"queryCacheDuration\":null,\"queryCacheDependency\":null,\"where\":null,\"limit\":\"1\",\"offset\":null,\"indexBy\":null,\"emulateExecution\":false}' WHERE `id`=26
2018-11-16 21:44:47 [-][1][-][trace][yii\db\Transaction::rollBack] Roll back transaction
2018-11-16 21:44:47 [-][1][-][error][venveo\bulkedit\services\BulkEdit::processHistoryItemsForElement] Transaction rolled back
2018-11-16 21:44:47 [-][1][-][error][venveo\bulkedit\queue\jobs\SaveBulkEditJob::execute] Could not save element in bulk edit job... SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'originalValue' at row 1
The SQL being executed was: UPDATE `bulkedit_history` SET `dateUpdated`='2018-11-17 02:44:47', `status`='completed', `originalValue`='{\"editable\":false,\"sectionId\":null,\"typeId\":null,\"authorId\":null,\"authorGroupId\":null,\"postDate\":null,\"before\":null,\"after\":null,\"expiryDate\":null,\"elementType\":\"craft\\\\elements\\\\Entry\",\"query\":null,\"subQuery\":null,\"contentTable\":\"{{%content}}\",\"customFields\":null,\"inReverse\":false,\"asArray\":false,\"id\":null,\"uid\":null,\"fixedOrder\":false,\"status\":[\"live\"],\"archived\":false,\"dateCreated\":null,\"dateUpdated\":null,\"siteId\":1,\"enabledForSite\":true,\"leaves\":false,\"relatedTo\":null,\"title\":null,\"slug\":null,\"uri\":null,\"search\":null,\"ref\":null,\"with\":null,\"orderBy\":{\"relations.sortOrder\":4},\"withStructure\":true,\"structureId\":null,\"level\":null,\"hasDescendants\":null,\"ancestorOf\":null,\"ancestorDist\":null,\"descendantOf\":null,\"descendantDist\":null,\"siblingOf\":null,\"prevSiblingOf\":null,\"nextSiblingOf\":null,\"positionedBefore\":null,\"positionedAfter\":null,\"select\":[\"**\"],\"selectOption\":null,\"distinct\":null,\"from\":null,\"groupBy\":null,\"join\":[[\"INNER JOIN\",\"{{%relations}} relations\",[\"and\",\"[[relations.targetId]] = [[elements.id]]\",{\"relations.sourceId\":\"1281\",\"relations.fieldId\":\"15\"},[\"or\",{\"relations.sourceSiteId\":null},{\"relations.sourceSiteId\":1}]]]],\"having\":null,\"union\":null,\"params\":[],\"queryCacheDuration\":null,\"queryCacheDependency\":null,\"where\":null,\"limit\":\"1\",\"offset\":null,\"indexBy\":null,\"emulateExecution\":false}' WHERE `id`=26
2018-11-16 21:44:47 [-][1][-][error][venveo\bulkedit\queue\jobs\SaveBulkEditJob::execute] Failed to save... Couldn’t save element 1281 (craft\elements\Entry)
2018-11-16 21:44:47 [-][1][-][error][craft\queue\QueueLogBehavior::afterError]  [206] Bulk Edit in progress by  (attempt: 1) - Error (time: 0.017s): Couldn’t save element 1281 (craft\elements\Entry)
2018-11-16 21:44:47 [-][1][-][error][yii\base\Exception] yii\base\Exception: Couldn’t save element 1281 (craft\elements\Entry) in /app/craft/vendor/venveo/craft-bulkedit/src/queue/jobs/SaveBulkEditJob.php:51
Stack trace:
#0 /app/craft/vendor/yiisoft/yii2-queue/src/Queue.php(214): venveo\bulkedit\queue\jobs\SaveBulkEditJob->execute(Object(craft\queue\Queue))
#1 /app/craft/vendor/yiisoft/yii2-queue/src/cli/Queue.php(147): yii\queue\Queue->handleMessage('206', 'O:42:"venveo\\bu...', '300', 1)
#2 /app/craft/vendor/craftcms/cms/src/queue/Queue.php(95): yii\queue\cli\Queue->handleMessage('206', 'O:42:"venveo\\bu...', '300', 1)
#3 /app/craft/vendor/craftcms/cms/src/controllers/QueueController.php(86): craft\queue\Queue->run()
#4 [internal function]: craft\controllers\QueueController->actionRun()
#5 /app/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#6 /app/craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#7 /app/craft/vendor/craftcms/cms/src/web/Controller.php(104): yii\base\Controller->runAction('run', Array)
#8 /app/craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('run', Array)
#9 /app/craft/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('queue/run', Array)
#10 /app/craft/vendor/craftcms/cms/src/web/Application.php(542): craft\web\Application->runAction('queue/run', Array)
#11 /app/craft/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#12 /app/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#13 /app/craft/web/index.php(21): yii\base\Application->run()
#14 {main}
2018-11-16 21:44:47 [-][1][-][info][yii\db\Command::execute] UPDATE `queue` SET `fail`=1, `dateFailed`='2018-11-17 02:44:47', `error`='Couldn’t save element 1281 (craft\\elements\\Entry)' WHERE `id`='206'
2018-11-16 21:44:47 [-][1][-][profile begin][yii\db\Command::execute] UPDATE `queue` SET `fail`=1, `dateFailed`='2018-11-17 02:44:47', `error`='Couldn’t save element 1281 (craft\\elements\\Entry)' WHERE `id`='206'
2018-11-16 21:44:47 [-][1][-][profile end][yii\db\Command::execute] UPDATE `queue` SET `fail`=1, `dateFailed`='2018-11-17 02:44:47', `error`='Couldn’t save element 1281 (craft\\elements\\Entry)' WHERE `id`='206'
2018-11-16 21:44:47 [-][1][-][info][yii\db\Command::query] SELECT *
FROM `queue`
WHERE ((`fail`=FALSE) AND (`timeUpdated` IS NULL)) AND (`timePushed` <= 1542422687 - `delay`)
ORDER BY `priority`, `id`
LIMIT 1
2018-11-16 21:44:47 [-][1][-][profile begin][yii\db\Command::query] SELECT *
FROM `queue`
WHERE ((`fail`=FALSE) AND (`timeUpdated` IS NULL)) AND (`timePushed` <= 1542422687 - `delay`)
ORDER BY `priority`, `id`
LIMIT 1
2018-11-16 21:44:47 [-][1][-][profile end][yii\db\Command::query] SELECT *
FROM `queue`
WHERE ((`fail`=FALSE) AND (`timeUpdated` IS NULL)) AND (`timePushed` <= 1542422687 - `delay`)
ORDER BY `priority`, `id`
LIMIT 1
```

**Comment by Mosnar** [comment]
I've released  v1.0.3 that should fix this issue. Let me know how that update works out for you!

**Comment by readtedium** [comment]
Thanks for working on this! I appreciate it. I'll let you know how the fix treats me. :)

**Comment by Mosnar** [comment]
Happy to help!

**Comment by chasegiunta** [comment]
@Mosnar Just installed this plugin today and ran into this error. I saw the applicable commit you made to fix this issue (changing column type from varchar to text) but looking at the database, the column type is still varchar. Is it possible the migration that fixes this issue isn't actually running?

**Comment by Mosnar** [comment]
Hey @chasegiunta, thanks for reaching out. My team and I will double-check this, could you please provide more specific details? Craft version, plugin version, and even more helpful, if you could send a copy of your composer.json and composer.lock files to ransom@venveo.com

This plugin is pending a major rewrite, as I'm not happy with the current codebase, but I would love to get your issues resolved if possible.

**Comment by chasegiunta** [comment]
@Mosnar it was pretty easy to resolve - I just went into the database manually and changed the column type from varchar to text. Was able to uninstall and reinstall and the issue was still present. It seems like the migration isn't running or perhaps being applied incorrectly. It was the latest of both Craft (3.1.5) & BulkEdit (1.0.3).

As a side note, would love to offer help in testing or feedback for your rewrite. I created a similar plugin for Craft 2 that tackled bulk editing a bit differently (https://github.com/chasegiunta/batch - not as good, IMO, I like your implementation better) for a specific project and am currently redoing that project in Craft 3. Thanks for creating this!

**Comment by Mosnar** [comment]
Thanks for the feedback, glad you were able to resolve it! I'll be pushing a new branch in the coming days for the refactor. Your Craft 2 plugin has some pretty cool features, would love to implement some of them here! If you ever want to contribute or send suggestions, hit me up in the Craft Slack channel
