### ISSUE TITLE
Job failed: Erroneous data format for unserializing 'ArrayObject'

### ISSUE THREAD

**Issue by daltonrooney** [venveo/craft-bulkedit#39]
My Bulk Edit jobs are failing with the error message: `Erroneous data format for unserializing 'ArrayObject'`

The job is attempting to remove an entry from an Entry field.

Any thoughts?

The job data looks like : 

```
{
    "context": {
        "ownerId": 118,
        "siteId": 1,
        "elementType": "craft\\elements\\Entry",
        "elementIds": "[\"108537\",\"108539\",\"108535\",\"108533\",\"108531\",\"108527\",\"108525\",\"108441\",\"108419\",\"108417\",\"108415\",\"108413\",\"108411\",\"108409\",\"108407\",\"108405\",\"108421\",\"108423\",\"108439\",\"108437\",\"108435\",\"108433\",\"108431\",\"108429\",\"108427\",\"108425\",\"108403\",\"108401\",\"108399\",\"108377\",\"108375\",\"108373\",\"108371\",\"108369\",\"108367\",\"108365\",\"108363\",\"108379\",\"108381\",\"108397\",\"108395\",\"108393\",\"108391\",\"108389\",\"108387\",\"108385\",\"108383\",\"108361\",\"108443\",\"108497\",\"108503\",\"108501\",\"108499\",\"108495\",\"108493\",\"108491\",\"108505\",\"108489\",\"108507\",\"108509\",\"108529\",\"108523\",\"108521\",\"108519\",\"108517\",\"108515\",\"108511\",\"108487\",\"108485\",\"108483\",\"108461\",\"108459\",\"108457\",\"108455\",\"108453\",\"108451\",\"108449\",\"108447\",\"108463\",\"108465\",\"108481\",\"108479\",\"108477\",\"108475\",\"108473\",\"108471\",\"108469\",\"108467\",\"108445\",\"108513\"]",
        "fieldIds": "[169]",
        "dateCreated": "2022-02-12 00:23:40",
        "dateUpdated": "2022-02-12 00:23:40",
        "uid": "176eb599-254b-4007-91d5-d803f4a8d807",
        "id": 3
    },
    "description": null
}
```

Found a stacktrace in the queue.log:

```
Next yii\queue\InvalidJobException: Erroneous data format for unserializing 'ArrayObject' in /home/webapps/jobsite-staging/releases/167/craft/vendor/yiisoft/yii2-queue/src/Queue.php:270
Stack trace:
#0 /home/webapps/jobsite-staging/releases/167/craft/vendor/yiisoft/yii2-queue/src/Queue.php(230): yii\queue\Queue->unserializeMessage('O:42:"venveo\\bu...')
#1 /home/webapps/jobsite-staging/releases/167/craft/vendor/yiisoft/yii2-queue/src/cli/Queue.php(162): yii\queue\Queue->handleMessage('142103', 'O:42:"venveo\\bu...', '300', '1')
#2 /home/webapps/jobsite-staging/releases/167/craft/vendor/yiisoft/yii2-queue/src/cli/Command.php(146): yii\queue\cli\Queue->execute('142103', 'O:42:"venveo\\bu...', '300', '1', '2395')
#3 [internal function]: yii\queue\cli\Command->actionExec('142103', '300', '1', '2395')
#4 /home/webapps/jobsite-staging/releases/167/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#5 /home/webapps/jobsite-staging/releases/167/craft/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#6 /home/webapps/jobsite-staging/releases/167/craft/vendor/yiisoft/yii2/console/Controller.php(182): yii\base\Controller->runAction('exec', Array)
#7 /home/webapps/jobsite-staging/releases/167/craft/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('exec', Array)
#8 /home/webapps/jobsite-staging/releases/167/craft/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('queue/exec', Array)
#9 /home/webapps/jobsite-staging/releases/167/craft/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('queue/exec', Array)
#10 /home/webapps/jobsite-staging/releases/167/craft/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('queue/exec', Array)
#11 /home/webapps/jobsite-staging/releases/167/craft/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest(Object(craft\console\Request))
#12 /home/webapps/jobsite-staging/releases/167/craft/craft(27): yii\base\Application->run()
#13 {main}
```

**Comment by daltonrooney** [comment]
Updated to Craft CMS 3.7.27.2 and now I'm getting a different error on the same job: `Could not save element in bulk edit job... array_diff(): Expected parameter 2 to be an array, string given`

```
2022-02-17 08:36:43 [-][118][-][trace][yii\db\Transaction::rollBack] Roll back transaction
2022-02-17 08:36:43 [-][118][-][error][venveo\bulkedit\services\BulkEdit::processHistoryItemsForElement] Transaction rolled back
2022-02-17 08:36:43 [-][118][-][error][venveo\bulkedit\queue\jobs\SaveBulkEditJob::execute] Could not save element in bulk edit job... array_diff(): Expected parameter 2 to be an array, string given
2022-02-17 08:36:43 [-][118][-][error][venveo\bulkedit\queue\jobs\SaveBulkEditJob::execute] Failed to save... Couldn’t save element 212341 (craft\elements\Entry)
2022-02-17 08:36:43 [-][118][-][error][craft\queue\QueueLogBehavior::afterError]  [170606] Bulk Edit in progress by Raygun (attempt: 1, pid: 741) - Error (time: 0.097s): Couldn’t save element 212341 (craft\elements\Entry)
2022-02-17 08:36:43 [-][118][-][error][yii\base\Exception] yii\base\Exception: Couldn’t save element 212341 (craft\elements\Entry) in /app/craft/vendor/venveo/craft-bulkedit/src/queue/jobs/SaveBulkEditJob.php:72
Stack trace:
#0 /app/craft/vendor/yiisoft/yii2-queue/src/Queue.php(246): venveo\bulkedit\queue\jobs\SaveBulkEditJob->execute(Object(craft\queue\Queue))
#1 /app/craft/vendor/yiisoft/yii2-queue/src/cli/Queue.php(147): yii\queue\Queue->handleMessage('170606', 'O:42:"venveo\\bu...', '1200', 1)
#2 /app/craft/vendor/craftcms/cms/src/queue/Queue.php(131): yii\queue\cli\Queue->handleMessage('170606', 'O:42:"venveo\\bu...', '1200', 1)
#3 [internal function]: craft\queue\Queue->craft\queue\{closure}(Object(Closure))
#4 /app/craft/vendor/yiisoft/yii2-queue/src/cli/Queue.php(117): call_user_func(Object(Closure), Object(Closure))
#5 /app/craft/vendor/craftcms/cms/src/queue/Queue.php(140): yii\queue\cli\Queue->runWorker(Object(Closure))
#6 /app/craft/vendor/craftcms/cms/src/controllers/QueueController.php(84): craft\queue\Queue->run()
#7 [internal function]: craft\controllers\QueueController->actionRun()
#8 /app/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /app/craft/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#10 /app/craft/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('run', Array)
#11 /app/craft/vendor/craftcms/cms/src/web/Application.php(287): yii\base\Module->runAction('queue/run', Array)
#12 /app/craft/vendor/craftcms/cms/src/web/Application.php(596): craft\web\Application->runAction('queue/run', Array)
#13 /app/craft/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#14 /app/craft/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#15 /app/public/index.php(26): yii\base\Application->run()
#16 {main}
2022-02-17 08:36:43 [-][118][-][info][yii\db\Command::query] SELECT GET_LOCK('2c50881bc85aacff3bf211b5bbc897d325485592', 5)
2022-02-17 08:36:43 [-][118][-][profile begin][yii\db\Command::query] SELECT GET_LOCK('2c50881bc85aacff3bf211b5bbc897d325485592', 5)
2022-02-17 08:36:43 [-][118][-][profile end][yii\db\Command::query] SELECT GET_LOCK('2c50881bc85aacff3bf211b5bbc897d325485592', 5)
2022-02-17 08:36:43 [-][118][-][error][yii\base\Exception] yii\base\Exception: Couldn’t save element 212341 (craft\elements\Entry) in /app/craft/vendor/venveo/craft-bulkedit/src/queue/jobs/SaveBulkEditJob.php:72
Stack trace:
#0 /app/craft/vendor/yiisoft/yii2-queue/src/Queue.php(246): venveo\bulkedit\queue\jobs\SaveBulkEditJob->execute(Object(craft\queue\Queue))
#1 /app/craft/vendor/yiisoft/yii2-queue/src/cli/Queue.php(147): yii\queue\Queue->handleMessage('170606', 'O:42:"venveo\\bu...', '1200', 1)
#2 /app/craft/vendor/craftcms/cms/src/queue/Queue.php(131): yii\queue\cli\Queue->handleMessage('170606', 'O:42:"venveo\\bu...', '1200', 1)
#3 [internal function]: craft\queue\Queue->craft\queue\{closure}(Object(Closure))
#4 /app/craft/vendor/yiisoft/yii2-queue/src/cli/Queue.php(117): call_user_func(Object(Closure), Object(Closure))
#5 /app/craft/vendor/craftcms/cms/src/queue/Queue.php(140): yii\queue\cli\Queue->runWorker(Object(Closure))
#6 /app/craft/vendor/craftcms/cms/src/controllers/QueueController.php(84): craft\queue\Queue->run()
#7 [internal function]: craft\controllers\QueueController->actionRun()
#8 /app/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /app/craft/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#10 /app/craft/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('run', Array)
#11 /app/craft/vendor/craftcms/cms/src/web/Application.php(287): yii\base\Module->runAction('queue/run', Array)
#12 /app/craft/vendor/craftcms/cms/src/web/Application.php(596): craft\web\Application->runAction('queue/run', Array)
#13 /app/craft/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#14 /app/craft/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#15 /app/public/index.php(26): yii\base\Application->run()
#16 {main}
```

**Comment by Mosnar** [comment]
@daltonrooney Apologies for the slow response. Are you able to provide the version of PHP you were using so I can test?

**Comment by daltonrooney** [comment]
Sure, thanks for following up! Relevant info:

PHP version 7.4.28
MySQL 5.5.5
Craft Pro 3.7.27.2
Bulk Edit 2.0.6

**Comment by Mosnar** [comment]
Thanks! I'm messing with it now and not having much luck. What field types are you updating and what strategy are you using? (e.g. Entries field with "subtraction" strategy)

**Comment by Mosnar** [comment]
Just tagged 4.0.0-RC1 with support for Craft 4 and quite a lot of infrastructure changes. Feel free to bump this issue if it continues to be a problem in the 4.0.0 version.

**Comment by daltonrooney** [comment]
So this was a bit of user error, I think. I am able to reproduce in Craft 4.3.1 with the current version of Bulk Edit. I was trying to remove an asset from all entries in a section.

1) Select all entries in the section and "Bulk Edit"
2) Enable the edit toggle on the `thumbnailImage` field with strategy of "Subtract"
3) Leave `thumbnailImage` field empty on the next screen and click "Save x Elements"

The error was caused because I was trying to subract... nothing. I tried again with a strategy of "Replace" and no thumbnail selected, and the job runs successfully as expected.


Entries field with subtraction strategy.
